// src/constants/roles.ts

export const ROLES = {
    ADMIN: "ADMIN",
    TECNICO: "TECNICO",
    CLIENTE: "CLIENTE",
    VENTAS: "VENTAS",
} as const;

export const ROLE_GROUPS = {
    // Incluimos 'ADMINISTRACION' como alias por compatibilidad con tokens existentes
    ADMIN_ONLY: [ROLES.ADMIN, "ADMINISTRACION"],
    FACTURACION: [ROLES.ADMIN, "ADMINISTRACION", ROLES.VENTAS],
    COTIZACIONES: [ROLES.ADMIN, "ADMINISTRACION", ROLES.VENTAS],
    HELPDESK: [ROLES.ADMIN, "ADMINISTRACION", ROLES.TECNICO],
    VISITAS: [ROLES.ADMIN, "ADMINISTRACION", ROLES.TECNICO],
    EMPRESAS_READ: [ROLES.ADMIN, "ADMINISTRACION", ROLES.TECNICO, ROLES.VENTAS],
};