// src/constants/roles.ts

export const ROLES = {
    ADMIN: "ADMIN",
    TECNICO: "TECNICO",
    CLIENTE: "CLIENTE",
    VENTAS: "VENTAS",
} as const;

export const ROLE_GROUPS = {
    ADMIN_ONLY: [ROLES.ADMIN],
    FACTURACION: [ROLES.ADMIN, ROLES.VENTAS],
    COTIZACIONES: [ROLES.ADMIN, ROLES.VENTAS],
    HELPDESK: [ROLES.ADMIN, ROLES.TECNICO],
    VISITAS: [ROLES.ADMIN, ROLES.TECNICO],
    EMPRESAS_READ: [ROLES.ADMIN, ROLES.TECNICO, ROLES.VENTAS],
};